"""Where IHE stops, and what this project does about it.

The mPSC IG's NEMSIS→FHIR mapping table is ~90% empty and EMS-Overall names no
ITI transaction numbers, so a working translator has to decide a great many
things the standard has not yet decided. Those decisions are legitimate — an
implementation that refused to act where the spec is silent would produce
nothing — but they are **not** conformance, and the difference has to survive
contact with a consumer who is validating against IHE and reasonably expects
our output to mean what the IG says.

This module is the single place that difference is declared.

## The two rules

**1. Reference other people's canonicals; never publish at them.**
A `coding.system` may point anywhere — that is a reference, and pointing NEMSIS
codes at the mPSC canonical is exactly right, because it keeps our data
conformant the day the IG stabilises. But shipping a `CodeSystem` *resource*
that claims `url = <the IHE canonical>` asserts we define that identifier. We
do not. Two different definitions at one canonical is a collision that breaks
any terminology server loading both, and the loser is whoever loaded ours
second. So: our artifacts carry OUR canonical, and say what they mirror.

**2. Canonical URLs resolve; naming systems need not.**
A canonical URL identifies fetchable content — a profile, a value set, a map —
so it belongs under a base we control and can serve. A *naming system* (the
`system` of an identifier or a `meta.tag`) identifies no document at all;
`urn:` is the honest form, and changing one is not cosmetic. `resource-id` in
particular is embedded in every conditional-update URL, so moving it would stop
matching resources already stored in a fhirEngine and silently duplicate the
lot. Those stay put, deliberately.

**3. Where the standard is silent, reach for the FHIR-native element before
inventing one.**
The temptation when an IG says nothing is to invent a structure that mirrors the
source format — a cluster of Observations shaped like the NEMSIS panel. That is
almost always wrong: base FHIR usually already has somewhere to put the fact,
and a receiver understands `Encounter.hospitalization.dischargeDisposition`
without reading a line of our documentation. An invented shape is understood by
nobody and conforms to nothing.

So every gap that mints an artifact must record which FHIR-native option was
considered and why it was insufficient. `Gap.native_alternative` carries that,
and the tests require it — an extension nobody argued against is an extension
nobody needed.

## The gap register

Every artifact we mint exists because the IG left a hole. `GAPS` records which
hole, verified against a dated build, and — the part that is usually missing
from work like this — **what makes it go away**. A local decision with no
retirement trigger is a permanent fork wearing a temporary label.
"""

from __future__ import annotations

from dataclasses import dataclass, field

#: Base for every canonical URL this project mints.
#:
#: A canonical URL is a permanent identifier: it is baked into every emitted
#: extension URL and is the thing a reviewer dereferences. So it is an owned
#: domain rather than a hosting vendor's subdomain — `fhirems.github.io` would
#: have tied this project's standards identity to where the files happen to
#: live this year. Domain-plus-path is also the shape every published IG takes
#: (hl7.org/fhir/us/core, profiles.ihe.net/PCC/mPSC).
#:
#: Hosting is a separate question and is currently GitHub Pages, served at this
#: domain via CNAME — the site is generated by `scripts/build-canonical-site.py`
#: so what resolves here is exactly what the package ships.
#:
#: Everything derives from this one constant; `docs/07_Conformance_and_Gaps.md`
#: carries the migration rule if it ever changes again.
CANONICAL_BASE = "https://emsinterop.com/fhir"

#: Canonicals owned by other people. We reference these and never define them.
FOREIGN_CANONICAL_PREFIXES = (
    "http://hl7.org/",
    "https://hl7.org/",
    "http://terminology.hl7.org/",
    "https://profiles.ihe.net/",
    "http://snomed.info/",
    "http://loinc.org",
    "http://www.nlm.nih.gov/",
    "http://unitsofmeasure.org",
)

#: Naming systems: the `system` of an identifier or tag. These name a scheme,
#: not a document, so they are URNs on purpose and are NOT migrated.
#:
#: `resource-id` is load-bearing for identity: it appears in every conditional
#: update URL, so changing it would fail to match already-stored resources and
#: duplicate them silently. Any change here is a data migration, not a rename.
NAMING_SYSTEMS = {
    "resource-id": "urn:emsinterop:resource-id",
    "mapping-ruleset": "urn:emsinterop:mapping-ruleset",
}


def canonical(kind: str, name: str) -> str:
    """Mint a canonical URL for something this project authors.

    `kind` is the resource type it belongs to (`StructureDefinition`,
    `ValueSet`, `ConceptMap`, `StructureMap`), so the URL is self-describing
    and matches the layout a published IG would serve.
    """
    return f"{CANONICAL_BASE}/{kind}/{name}"


def is_foreign(url: str) -> bool:
    """Is this canonical someone else's to define?"""
    return url.startswith(FOREIGN_CANONICAL_PREFIXES)


def is_ours(url: str) -> bool:
    return url.startswith(CANONICAL_BASE + "/")


@dataclass(frozen=True)
class Gap:
    """One thing the IHE profiles leave open, and how we occupy it."""

    id: str
    #: What the IG does not say, as verified — not as remembered.
    finding: str
    #: Where that was checked, and when. A gap report with no date is a rumour
    #: about a moving CI build.
    source: str
    verified: str
    #: What we do instead, and why it is defensible.
    decision: str
    #: Canonicals/artifacts this decision produces, if any.
    artifacts: tuple[str, ...] = ()
    #: What ends this. Without one, "interim" is a permanent fork.
    retirement: str = ""
    #: The upstream proposal that would close it, if we have written one.
    proposal: str = ""
    #: Does the decision change bytes a consumer receives?
    affects_output: bool = True
    #: Rule 3: which FHIR-native representation was considered first, and why
    #: it does not carry the fact. Required whenever this gap mints a
    #: StructureDefinition — inventing a shape when base FHIR already has one
    #: produces something no receiver understands.
    native_alternative: str = ""


#: Verified against the mPSC v2.0.0-draft CI build (footer 2025-10-30) and the
#: EMS-Overall build, on the dates below. Re-probe before relying on any of it:
#: these are CI builds and they move.
#:
#: Last full re-probe 2026-08-13: the mPSC build had NOT moved (same
#: 2025-10-30 footer, same 2.0.0-draft), and every finding still holds. Two
#: entries were nonetheless corrected, because the register had drifted from
#: what the build actually says rather than the build changing under it — the
#: mapping table is 98% empty rather than "~90-95%", and the Composition
#: defines four section slices rather than three. Re-probing is worth doing
#: even when nothing upstream moved.
GAPS: tuple[Gap, ...] = (
    Gap(
        id="mapping-table-empty",
        finding="NEMSIS-Mapping.html leaves the FHIR-path column empty on 440 "
                "of 449 element rows (98%). The nine populated rows are all "
                "dAgency.* -> Organization.identifier/name/address; every "
                "clinical panel is empty.",
        source="https://build.fhir.org/ig/IHE/PCC.PCS/NEMSIS-Mapping.html",
        verified="2026-08-13",
        decision="Author the complete field-level mapping for all NEMSIS 3.5 "
                 "national elements (ADR-005), dispositioning every element as "
                 "Mapped/Seeded/Deferred rather than dropping any.",
        artifacts=(
            "contrib/fieldmap/",
            # The logical models are the SOURCE side of the StructureMaps. They
            # exist only because the IG publishes no computable mapping: FML
            # needs a typed source definition, and NEMSIS panels have none in
            # FHIR. They retire with the rest of this gap.
            canonical("StructureDefinition", "NemsisEPatient"),
            canonical("StructureDefinition", "NemsisESituation"),
            canonical("StructureDefinition", "NemsisEVitalsGroup"),
            canonical("StructureDefinition", "NemsisEMedicationGroup"),
            canonical("StructureDefinition", "NemsisEProcedureGroup"),
        ),
        retirement="IHE populates the FHIR-path column. Ours then becomes a "
                   "conformance test against theirs rather than the source.",
        proposal="proposal-01",
        native_alternative="A FHIR logical model IS the native mechanism for "
                           "typing a non-FHIR source so FML can consume it — "
                           "that is what StructureDefinition.kind = "
                           "'logical' exists for. These describe NEMSIS "
                           "panels, which by definition have no FHIR "
                           "representation to reuse, and none of them appears "
                           "in emitted data.",
    ),
    Gap(
        id="composition-sections",
        finding="The Medical Summary Composition profile defines FOUR section "
                "slices — Problems, Allergies, Medications and Payers — with "
                "open slicing, and none for vitals, procedures, EMS course or "
                "narrative. (An earlier reading of this register said three and "
                "omitted Payers; the assembler always knew about it, the "
                "register did not.)",
        source="https://build.fhir.org/ig/IHE/PCC.PCS/"
               "StructureDefinition-IHE.PCC.FHIR.MS.Composition.html",
        verified="2026-08-13",
        decision="Emit the IG's four sections, plus additional LOINC-coded "
                 "ones the IG does not define (Vital Signs 8716-3, Procedures "
                 "47519-4, EMS Narrative 28568-4, EMS Course 46240-8). The "
                 "profile's slicing is OPEN, so the additions are conformant, "
                 "not a deviation — most clinical panels would otherwise have "
                 "no home in the document at all.",
        retirement="mPSC defines its own clinical sections. Ours align to the "
                   "codes it picks; where they differ, theirs win.",
        proposal="proposal-04",
    ),
    Gap(
        id="nemsis-codesystem-placeholders",
        finding="CodeSystem-NEMSIS still contains placeholder concepts whose "
                "displays read 'TODO: JFM do not know', 'TODO: JFM did not know "
                "either' and 'TODO: JFM completely clueless', including the "
                "malformed codes 99270235, C7 and todo1 (all three re-confirmed "
                "present).",
        source="https://build.fhir.org/ig/IHE/PCC.PCS/CodeSystem-NEMSIS.html",
        verified="2026-08-13",
        decision="Keep REFERENCING the mPSC canonical in coding.system so our "
                 "data is conformant the day the IG is fixed, but publish our "
                 "registry-derived CodeSystem (2,321 concepts, content=fragment) "
                 "under our OWN canonical. Publishing ours at theirs would be two "
                 "conflicting definitions of one identifier.",
        artifacts=(canonical("CodeSystem", "nemsis-registry"),),
        retirement="IHE publishes a usable NEMSIS CodeSystem. We then drop ours "
                   "and rely on theirs; no coding.system changes, because we "
                   "never stopped pointing at it.",
        proposal="proposal-02",
        affects_output=False,
    ),
    Gap(
        id="outcome-delegated-to-qore",
        finding="eOutcome.01/.02/.03 rows delegate to the QRPH 'QORE' profile. "
                "'QORE' appears as bare text with no link, binding or profile "
                "reference anywhere in the IG, and those rows carry no FHIR "
                "path.",
        source="https://build.fhir.org/ig/IHE/PCC.PCS/NEMSIS-Mapping.html",
        verified="2026-08-13",
        decision="Use the FHIR-native representation rather than inventing a "
                 "shape: discharge disposition rides on "
                 "Encounter.hospitalization.dischargeDisposition (NUBC-coded, "
                 "the vocabulary eOutcome.01/.02 already speak) with "
                 "hospitalization.destination for the receiving facility. The "
                 "inbound loop (ADT^A03 / FHIR discharge summary) writes "
                 "eOutcome back into NEMSIS for the state registry rather than "
                 "modelling it a second time in FHIR. Nothing bespoke is "
                 "emitted; what is missing is an IHE-blessed PROFILE to claim, "
                 "not a place to put the data.",
        retirement="QORE is published with a binding. We then claim it; the "
                   "underlying elements are already the FHIR-native ones, so "
                   "this is a claim to add rather than a model to replace.",
        native_alternative="Encounter.hospitalization.dischargeDisposition and "
                           ".destination — used, not merely considered.",
        proposal="proposal-05",
    ),
    Gap(
        id="prior-care-vitals-flag",
        finding="The eVitals.02 row (\"Obtained Prior to this Unit's EMS "
                "Care\", R [1..1]) has both mapping columns empty. FHIR has no "
                "element for the distinction and the IG proposes none, so it is "
                "lost on every vital sign unless carried some other way.",
        source="https://build.fhir.org/ig/IHE/PCC.PCS/NEMSIS-Mapping.html",
        verified="2026-08-13",
        decision="Carry it in a project extension. A reading taken by a prior "
                 "crew is a materially different clinical claim from one this "
                 "crew took, and silently flattening the two is the kind of "
                 "loss this project exists to prevent.",
        artifacts=(canonical("StructureDefinition",
                             "ems-obtained-prior-to-unit-care"),),
        retirement="IHE or US Core defines an equivalent. Dual-carry for one "
                   "minor release, then drop ours — the pattern ADR-006 already "
                   "uses for US Core vs pcc-uv race/ethnicity.",
        native_alternative="Observation.performer names WHO took the reading, "
                           "which a NEMSIS record often does not know, and "
                           "Provenance describes how a resource came to be "
                           "rather than a clinical circumstance of the "
                           "measurement. eVitals.02 is neither: it is a flag "
                           "that the reading predates this unit's care. No base "
                           "R4 or US Core element carries it, so an extension "
                           "is the honest answer.",
    ),
    Gap(
        id="no-source-version-pin",
        finding="No NEMSIS version is declared anywhere on the mapping page — "
                "zero occurrences of any 'NEMSIS 3.x' string — so the source "
                "scope is ambiguous between 3.4, 3.5.0 and 3.5.1.",
        source="https://build.fhir.org/ig/IHE/PCC.PCS/NEMSIS-Mapping.html",
        verified="2026-08-13",
        decision="Pin explicitly to NEMSIS 3.5.0 and handle 3.5.1 as declared "
                 "deltas (ADR-007), rather than guessing what the table means.",
        retirement="IHE pins a version. If it differs from 3.5.0, that is a "
                   "scope change for this project, not a mapping tweak.",
        proposal="proposal-03",
        affects_output=False,
    ),
    Gap(
        id="transport-binding-loose",
        finding="EMS-Overall names no ITI transaction numbers at all — zero "
                "occurrences of any 'ITI-nn' string on the index; the transport "
                "binding is described narratively.",
        source="https://build.fhir.org/ig/IHE/EMS-Overall/",
        verified="2026-08-13",
        decision="Treat transport as a pluggable interface with ITI-65 (MHD "
                 "Provide Document Bundle) as the default binding (ADR-008), so "
                 "a different binding is configuration rather than a rewrite.",
        retirement="EMS-Overall names its transactions. The default changes to "
                   "whatever it names; the interface does not.",
        proposal="proposal-06",
        affects_output=False,
    ),
)

GAPS_BY_ID = {gap.id: gap for gap in GAPS}

#: Every canonical this project is allowed to mint. Anything we publish that is
#: not in here is either an oversight or an undeclared local decision, and the
#: conformance tests refuse both.
def registered_artifacts() -> set[str]:
    return {art for gap in GAPS for art in gap.artifacts if art.startswith("http")}


def summary() -> dict:
    """A machine-readable statement of what is IHE's and what is ours.

    Emitted alongside the terminology package so a consumer can answer "which
    parts of this are the standard?" without reading our source."""
    return {
        "canonicalBase": CANONICAL_BASE,
        "namingSystems": NAMING_SYSTEMS,
        "gaps": [
            {
                "id": gap.id,
                "finding": gap.finding,
                "source": gap.source,
                "verified": gap.verified,
                "decision": gap.decision,
                "artifacts": list(gap.artifacts),
                "retirement": gap.retirement,
                "proposal": gap.proposal,
                "affectsOutput": gap.affects_output,
                # Rule 3's argument travels with the package: a consumer asking
                # "why is there an extension here?" gets the answer without
                # reading our source.
                "nativeAlternative": gap.native_alternative,
            }
            for gap in GAPS
        ],
    }
